### ISSUE TITLE
Uncaught TypeError: Return value of Diginize\WpVereinsflieger\VereinsfliegerApi\Responses\LoginFailedResponse::getNeed2fa() must be of the type int, null returned

### ISSUE THREAD

**Issue by silviokennecke** [Diginize/wp-vereinsflieger#18]
**Describe the bug**

Wordpress reported an error:

```
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 19 der Datei /srv/www/.../wp-content/plugins/wp-vereinsflieger/src/VereinsfliegerApi/Responses/LoginFailedResponse.php verursacht. Fehlermeldung: Uncaught TypeError: Return value of Diginize\WpVereinsflieger\VereinsfliegerApi\Responses\LoginFailedResponse::getNeed2fa() must be of the type int, null returned in /srv/www/.../wp-content/plugins/wp-vereinsflieger/src/VereinsfliegerApi/Responses/LoginFailedResponse.php:19
Stack trace:
#0 /srv/www/.../wp-content/plugins/wp-vereinsflieger/src/Api.php(80): Diginize\WpVereinsflieger\VereinsfliegerApi\Responses\LoginFailedResponse->getNeed2fa()
#1 /srv/www/.../wp-content/plugins/wp-vereinsflieger/src/WpPublic/Authentication.php(146): Diginize\WpVereinsflieger\Api->login('cummulus', 'e10adc3949ba59a...', NULL)
#2 /srv/www/.../wp-content/plugins/wp-vereinsflieger/src/WpPublic/Authentication.php(78): Diginize\WpVereinsflieger\WpPublic\Authentication->tryLogin('cummulus', 'e10adc3949ba59a...', NULL)
#3 /srv/www/.../wp-content/plugins/wp-vereinsflieger/src/WpPublic/Authentication.php(63): Diginize\WpVereinsflieger\WpPublic\Authentication->auth
```

**Environment**

```
WordPress-Version: 5.5.3
WP Vereinsflieger Version: 1.0.9
PHP-Version: 7.3.25
```

**Comment by tim010296** [comment]
Notiz: Die Fehlermeldung tauchte zwar nicht mehr auf, aber die Anmeldung ging trotzdem nicht, nur als Hinweis, falls es hilfreich ist.

**Comment by tim010296** [comment]
Any news on this?
